- projects/payment-lib/src/lib/components/card-details/card-details.component.html
- projects/payment-lib/src/lib/components/payment-list/payment-list.component.html
- projects/payment-lib/src/lib/components/payment-list/payment-list.component.ts
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.html
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.ts
- projects/payment-lib/src/lib/components/status-history/status-history.component.html
https://tools.hmcts.net/jira/browse/RDM-2578
Address some navigation issues
Remove page titles
Fix styling of grid rows and links
Update error wording and navigation
> RDM-2578: Update web components

- projects/payment-lib/src/lib/payment-lib.module.ts
Jira Link: https://tools.hmcts.net/jira/browse/RDM-4677
```
[ ] Yes
[X] No
```
> BrowserModule should not be imported by libraries

- package.json
- projects/payment-lib/package.json
> Updated package json for version 1.8.4

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.html
> Added empty array check for remissions on payment view

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.html
> PAY-1693 Payment view page header alignment

- package.json
- projects/payment-lib/package.json
> Updated version to 1.7.9

- package.json
- projects/payment-lib/package.json
> update the major version

- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
- src/app/components/payment-lib-int/payment-lib-int.component.html
> adding total to be paid

- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
remove the fee description to be done later when api ready
```
[ ] Yes
[ ] No
```
> adding heading to fee summary page

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
- src/app/components/payment-lib-int/payment-lib-int.component.html
- wire-mock/__files/case-txns/1111-2222-3333-0001_case_txns.json
- wire-mock/__files/case-txns/1111-2222-3333-0002_case_txns.json
- wire-mock/__files/case-txns/1111-2222-3333-0003_case_txns.json
- wire-mock/__files/case-txns/1111-2222-3333-0004_case_txns.json
- wire-mock/__files/case-txns/1111-2222-3333-4444_case_txns.json
- wire-mock/mappings/1111-2222-3333-0001_case_txns.json
- wire-mock/mappings/1111-2222-3333-4444_case_txns.json
> PAY-1835 Refactored to support the response json

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
- wire-mock/__files/case-txns/1111-2222-3333-0001_case_txns.json
- wire-mock/__files/case-txns/1111-2222-3333-0002_case_txns.json
- wire-mock/__files/case-txns/1111-2222-3333-0004_case_txns.json
- wire-mock/__files/case-txns/1111-2222-3333-0005_case_txns.json
- wire-mock/mappings/1111-2222-3333-0006_case_txns.json
> PAY-1787 Fixed the issue for no payments

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/payment-lib.component.ts
> PAY-1787 Remission table labels updated

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.html
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.ts
update how to calculate the remission amount
```
[ ] Yes
[ ] No
```
> update to display fee description in confirm remission page

- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
https://tools.hmcts.net/jira/browse/PAY-1879
TEL - MVP: Fee selection - fixed and flat fee selected
```
[ ] Yes
[x] No
```
> Adding redirect functionality for add new fee button

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
> PAY-1906 Add payment button linked to fee-summary page

- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
- projects/payment-lib/src/lib/payment-lib.component.ts
- src/app/components/ccd-search/ccd-search.component.ts
- src/app/components/payment-lib-int/payment-lib-int.component.html
- src/app/components/payment-lib-int/payment-lib-int.component.ts
> Rename the parameter from 'enableButton' to 'takePayment'

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- wire-mock/__files/case-txns/1111-2222-3333-0001_case_txns.json
- wire-mock/__files/case-txns/1111-2222-3333-0002_case_txns.json
- wire-mock/__files/case-txns/1111-2222-3333-0004_case_txns.json
- wire-mock/__files/case-txns/1111-2222-3333-0005_case_txns.json
- wire-mock/__files/case-txns/1111-2222-3333-0006_case_txns.json
> Fixed null payment and remission for case-transactions page

- projects/payment-lib/src/lib/payment-lib.component.ts
> Removing unwanted if statement

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.ts
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.scss
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
- projects/payment-lib/src/lib/interfaces/PaymentToPayhubRequest.ts
- projects/payment-lib/src/lib/payment-lib.module.ts
- projects/payment-lib/src/lib/pipes/sanitize-html.pipe.ts
- projects/payment-lib/src/lib/pipes/sanitize-html.spec.ts
- projects/payment-lib/src/lib/services/payment-view/payment-view.service.ts
> adding take payment in the fee-summary

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/interfaces/PaymentToPayhubRequest.ts
> update the provider for pci pal

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.ts
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
- projects/payment-lib/src/lib/services/payment-view/payment-view.service.ts
- projects/payment-lib/src/lib/services/shared/error-handler.service.ts
> adding more console log to debug the issue on send to payhub debugging

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
- projects/payment-lib/src/lib/interfaces/PaymentToPayhubRequest.ts
- projects/payment-lib/src/lib/services/payment-view/payment-view.service.ts
- projects/payment-lib/src/lib/services/shared/error-handler.service.ts
removing all the loggings
```
[ ] Yes
[ ] No
```
> fixing send to payhub issue

- projects/payment-lib/src/lib/components/add-remission/add-remission.component.html
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.scss
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.ts
https://tools.hmcts.net/jira/browse/PAY-1914
https://tools.hmcts.net/jira/browse/PAY-1915
TEL - MVP: Error messages - Remission reference missing and Amount
```
[ ] Yes
[x] No
```
> PAY-1914 and 1915 Add remission form validation changes

- projects/payment-lib/src/lib/components/add-remission/add-remission.component.html
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.ts
> PAY-1914 Validation pattern issue fixes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
> PAY-1943 Outstanding balance is now calculated for success status payments

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
> fee summary back button issue fixes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
> Converting time format from 12hrs to 24hrs

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.html
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.ts
- wire-mock/mappings/1111-2222-3333-0001_payment_details1.json
> PAY-1926 Case transactions paged linked to payment view

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.ts
> fixing the add remission callback to display button on ccd case page

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.scss
> applying camel case for juridiction in fee search page

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
https://tools.hmcts.net/jira/browse/PAY-1991
Payment Status History changes
```
[ ] Yes
[x ] No
```
> PAY-1991 Payment Status History changes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.html
Fee description changes
```
[ ] Yes
[x] No
```
> Fee description changes

- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
https://tools.hmcts.net/jira/browse/PAY-2114
updated the below 2 files
projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
```
[ ] Yes
[X ] No
```
> PAY-2114 Remove back button from pci pal screen

- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
https://tools.hmcts.net/jira/browse/PAY-2114
projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html modified:   projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
```
[ ] Yes
[ X] No
```
> PAY-2114 remove back button from PCI PAL

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
> hotfix - fixing pci pal url issue

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.ts
> Payment view component back link issue fixes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.html
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.ts
> removing redirection back link changes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.ts
- projects/payment-lib/src/lib/payment-lib.module.ts
- projects/payment-lib/src/lib/services/payment-view/payment-view.service.ts
- projects/payment-lib/src/lib/services/shared/httpclient/webcomponent.http.client.spec.ts
- projects/payment-lib/src/lib/services/shared/httpclient/webcomponent.http.client.ts
> CSRF Token issue fixes

- package.json
- projects/payment-lib/package.json
> Version change

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/allocate-payments/allocate-payments.component.html
https://tools.hmcts.net/jira/browse/PAY-2674
PAY-2674 - adding hyphen if volume empty
```
[ ] Yes
[x] No
```
> PAY-2674 - adding hyphen if volume empty

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.html
- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.ts
> TextChange

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.scss
- projects/payment-lib/src/lib/components/reports/reports.component.html
https://tools.hmcts.net/jira/browse/PAY-2697
Auto-populate Site ID for transferring a payment/case
```
[ ] Yes
[x] No
```
> UAT issue fixes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/card-details/card-details.component.html
- projects/payment-lib/src/lib/components/reports/reports.component.ts
- projects/payment-lib/src/lib/services/xl-file/xl-file.service.ts
PAY-2715
```
[ ] Yes
[X ] No
```
> Report changes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/reports/reports.component.ts
> Pay 2113 new

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/reports/reports.component.ts
> Pay 3688 issue fixes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
- projects/payment-lib/src/lib/interfaces/AllocatePaymentRequest.ts
> Pay 3472 fr telephoney

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.ts
> PAY-3752 transferred reason changes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.html
- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.scss
- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.ts
- projects/payment-lib/src/lib/services/payment-view/payment-view.service.ts
> Pay 3732 siteid dropdown

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
> Exception Changes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.css
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.html
> Pay 3521 transaction id display

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.ts
- projects/payment-lib/src/lib/components/allocate-payments/allocate-payments.component.ts
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.html
- projects/payment-lib/src/lib/components/fee-summary/fee-summary.component.ts
- projects/payment-lib/src/lib/components/mark-unidentified-payment/mark-unidentified-payment.component.ts
- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.ts
- projects/payment-lib/src/lib/components/unprocessed-payments/unprocessed-payments.component.ts
- projects/payment-lib/src/lib/interfaces/AddRemissionRequest.ts
- projects/payment-lib/src/lib/interfaces/AllocatePaymentRequest.ts
- projects/payment-lib/src/lib/interfaces/PaymentToPayhubRequest.ts
- projects/payment-lib/src/lib/payment-lib.component.ts
- yarn.lock
> Pay 3902 orgid api changes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/allocate-payments/allocate-payments.component.html
- projects/payment-lib/src/lib/components/allocate-payments/allocate-payments.component.ts
- projects/payment-lib/src/lib/components/reports/reports.component.html
- projects/payment-lib/src/lib/components/reports/reports.component.ts
- projects/payment-lib/src/lib/services/xl-file/xl-file.service.ts
> Pay 5223&4953v3

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/allocate-payments/allocate-payments.component.ts
- projects/payment-lib/src/lib/components/reports/reports.component.html
- projects/payment-lib/src/lib/components/reports/reports.component.ts
- projects/payment-lib/src/lib/services/xl-file/xl-file.service.ts
> Pay 4953v2

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/allocate-payments/allocate-payments.component.ts
- projects/payment-lib/src/lib/components/reports/reports.component.html
- projects/payment-lib/src/lib/components/reports/reports.component.ts
- projects/payment-lib/src/lib/services/xl-file/xl-file.service.ts
> Pay 4953 v3

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/allocate-payments/allocate-payments.component.ts
- projects/payment-lib/src/lib/components/reports/reports.component.html
- projects/payment-lib/src/lib/components/reports/reports.component.ts
- projects/payment-lib/src/lib/services/xl-file/xl-file.service.ts
> Pay 4953 v4

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/services/refunds/refunds.service.ts
- projects/payment-lib/src/lib/services/shared/httpclient/webcomponent.http.client.ts
> Browser Issue

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.css
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.html
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.ts
- projects/payment-lib/src/lib/components/pba-payment/pba-payment.component.html
- projects/payment-lib/src/lib/components/pba-payment/pba-payment.component.scss
- projects/payment-lib/src/lib/components/pba-payment/pba-payment.component.spec.ts
- projects/payment-lib/src/lib/components/pba-payment/pba-payment.component.ts
- projects/payment-lib/src/lib/components/service-request/service-request.component.css
- projects/payment-lib/src/lib/components/service-request/service-request.component.html
- projects/payment-lib/src/lib/components/service-request/service-request.component.ts
- projects/payment-lib/src/lib/interfaces/IserviceRequestCardPayment.ts
- projects/payment-lib/src/lib/interfaces/IserviceRequestPbaPayment.ts
- projects/payment-lib/src/lib/payment-lib.component.spec.ts
- projects/payment-lib/src/lib/payment-lib.component.ts
- projects/payment-lib/src/lib/payment-lib.module.ts
- projects/payment-lib/src/lib/payment-lib.service.ts
- projects/payment-lib/src/lib/services/payment-view/payment-view.service.ts
- projects/payment-lib/src/lib/services/refunds/refunds.service.ts
- projects/payment-lib/src/lib/services/shared/httpclient/webcomponent.http.client.ts
- yarn.lock
> Epic ways2pay v1

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
- projects/payment-lib/src/lib/components/refund-status/refund-status.component.html
- projects/payment-lib/src/lib/components/refund-status/refund-status.component.ts
- projects/payment-lib/src/lib/payment-lib.component.ts
> 4xx issue fixes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/reports/reports.component.ts
> payment failure report changes

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/contact-details/contact-details.component.ts
- projects/payment-lib/src/lib/components/refund-status/refund-status.component.html
- projects/payment-lib/src/lib/components/refund-status/refund-status.component.ts
> Refunds V2

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/refund-status/refund-status.component.ts
> Resumbit Refund Volume fix

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/pba-payment/pba-payment.component.ts
> Disable Payment button once clicked

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/unprocessed-payments/unprocessed-payments.component.ts
JIRA link (if applicable) 
https://tools.hmcts.net/jira/browse/SNI-3692
Change description
Allocate to existing service request not being enabled correctly
[ ] Yes
[x] No
> SNI-3692 validateButtons fix

- .gitignore
- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/unprocessed-payments/unprocessed-payments.component.ts
https://tools.hmcts.net/jira/browse/PAY-5980
Revert SNI-3692.
```
[ ] Yes
[x] No
```
> PAY-5980: Revert SNI-3692.

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/unprocessed-payments/unprocessed-payments.component.ts
https://tools.hmcts.net/jira/browse/SNI-3692
Allocate to new or existing Service request button fix.
```
[ ] Yes
[x] No
```
> SNI-3692 version change to 5.2.9-beta08

- .github/renovate.json
PAY_6492
rennovate solution added
```
[ ] Yes
[ x ] No
```
> rennovate solution added

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
- projects/payment-lib/src/lib/components/process-refund/process-refund.component.ts
- projects/payment-lib/src/lib/components/service-request/service-request.component.ts
https://tools.hmcts.net/jira/browse/PAY-6374
Party Name not displaying correctly
```
[ ] Yes
[X] No
```
> PAY-6374 Party name corrected and version updated.

- package.json
- projects/payment-lib/package.json
https://tools.hmcts.net/jira/browse/PAY-6374
Updating version to 5.2.12 as 5.2.10 had already been published.
> PAY-6374: Update version to release version

- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.spec.ts
- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.ts
- projects/payment-lib/src/lib/services/shared/error-handler.service.ts
Reverts hmcts/ccpay-web-component#322
> Revert "PAY-6586"

- package.json
- projects/payment-lib/package.json
PAY-6586
update web component version
> PAY-6586 version update 6.0.8

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.spec.ts
- projects/payment-lib/src/lib/components/mark-unsolicited-payment/mark-unsolicited-payment.component.ts
- projects/payment-lib/src/lib/services/shared/error-handler.service.ts
https://tools.hmcts.net/jira/browse/PAY-6586
Reverted the revert for PAY-6586 and set version to 6.0.9
> PAY-6586 Reverted revert & version 6.0.9

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/reports/reports.component.ts
https://tools.hmcts.net/jira/browse/PAY-6817
Fix to initialise reports correctly so they can be used without forcing an error first.
> PAY-6817 Initialise Reports fix

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/reports/reports.component.ts
https://tools.hmcts.net/jira/browse/PAY-6817
Added missing changes to report page to fix the initialisation of the reports after release of 6.0.11.
> PAY-6817: Added missing changes in release to fix reports

- yarn-audit-known-issues
PAY-6830
Surpression fix
- [ x ] Does this PR introduce a breaking change
> surpression fix

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.html
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.spec.ts
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.ts
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.html
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.spec.ts
- projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.html
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.spec.ts
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.ts
- projects/payment-lib/src/lib/components/pba-payment/pba-payment.component.html
- projects/payment-lib/src/lib/components/pba-payment/pba-payment.component.spec.ts
- projects/payment-lib/src/lib/components/pba-payment/pba-payment.component.ts
- projects/payment-lib/src/lib/components/service-request/service-request.component.html
- projects/payment-lib/src/lib/components/service-request/service-request.component.spec.ts
- projects/payment-lib/src/lib/components/service-request/service-request.component.ts
- projects/payment-lib/src/lib/interfaces/IserviceRequestCardPayment.ts
- projects/payment-lib/src/lib/payment-lib.module.ts
- src/app/app.module.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/PAY-2787
https://tools.hmcts.net/jira/browse/PAY-6731
https://tools.hmcts.net/jira/browse/PAY-6732
- [ x ] commit messages are meaningful and follow good commit message guidelines
- [ x ] README and other documentation has been updated / added (if needed)
- [ x ] tests have been updated / new tests has been added (if needed)
- [  ] Does this PR introduce a breaking change
> Pay 6731 welsh translation

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/add-remission/add-remission.component.ts
https://tools.hmcts.net/jira/browse/PAY-6806
Reverting change for a telephone payment with upfront remission redirecting to the wrong location.
> Reverting PAY-6806

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/components/payment-view/payment-view.component.html
- [ x ] commit messages are meaningful and follow good commit message guidelines
> fixes an erroneous implementation of the translation service

- package.json
- projects/payment-lib/package.json
- projects/payment-lib/src/lib/services/xl-file/xl-file.service.ts
https://tools.hmcts.net/jira/browse/PAY-7120
To addres vulnerability VUL-6113
> PAY-7120 version set to 6.2.5-beta01

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/CME-501
The release of CME-501 occurred with the pre-release version of rpx-xui-translation.  This pr is to update this to use the official release version. 
Build tests should suffice.
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> CME-501 update the version to the release version
